# -*- coding: utf-8 -*-
{   'active': False,
    'author': 'No author.',
    'category': 'base.module_category_hidden',
    'data': [   u'security/epicor_group.xml',
                u'view/loader_view.xml',
                u'data/loader_properties.xml',
                u'data/loader_track.xml',
                u'workflow/loader_workflow.xml',
                'security/ir.model.access.csv',
                u'view/epicor_menuitem.xml',
                u'view/epicor_actions.xml'],
    'depends': [u'mail'],
    'description': 'No documented',
    'installable': True,
    'license': 'AGPL-3',
    'name': 'epicor',
    'test': [],
    'version': 'No version',
    'website': ''}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
